Add Junit test
AY2324S2-CS2113-T12-1/tp pull request #22
Opened 2024-03-20 01:00 UTC by anneleong

please accept my lovely team :)

2024-03-20 01:09 UTC, BenjoBurger requested changes
The check failed, please check your checkstyle!

2024-03-21 02:55 UTC, ningsongshen approved these changes

2024-03-21 02:56 UTC, ningsongshen approved these changes

2024-03-21 03:21 UTC, BenjoBurger approved these changes
LGTM :+1:

2024-03-21 03:22 UTC, merged